version: "3.7"
services:
  webapp:
    build: .
    restart: always
    volumes:
      - web_static:/usr/src/elephant_vending_machine/elephant_vending_machine
    
  webproxy:
    image: nginx
    restart: always
    volumes:
      - web_static:/var/www-data
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  web_static:
