version: "3.7"
services:
  webapp:
    build: .
    restart: always
    volumes:
      - web_static:/elephant_vending_machine/elephant_vending_machine
    networks:
      - web_network
        
  webproxy:
    image: nginx
    restart: always
    volumes:
      - web_static:/var/www-data
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - web_network
    ports:
      - "8080:80"
  
networks:
  web_network:

volumes:
  web_static:
