version: "3.7"
services:
  webapp:
    build: .
    volumes:
      - type: volume
        source: web_static
        target: /elephant_vending_machine/static
    networks:
      - web_network
  webproxy:
    image: nginx
    volumes:
      - type: volume
        source: web_static
        target: /var/www-data
      - type: bind
        source: ./nginx_conf
        target: /etc/nginx/conf.d
    networks:
      - web_network
    ports:
      - "8080:80"
  
networks:
  web_network:
    ipam:
      config:
        - subnet: "192.168.100.0/24"

volumes:
  web_static: